### ISSUE TITLE
CPU占用过高，

### ISSUE THREAD

**Issue by twosson** [twosson/fildr-cli#7]
### Relevant ./fildr/config.toml:

```toml
help = false
home = "/Users/twosson"

[gateway]
  evaluation = "5s"
  instance = ""
  token = "..."
  url = "https://api.fildr.com/fildr-miner"

[lotus]

  [lotus.daemon]
    enable = false
    ip = "193.112.74.252"
    port = 1234
```

### System info:

Version:  (dev-version)
Git commit:  ddbc2cf
Built:  2020-07-17T08:45:59Z

mac book
